### ISSUE TITLE
Update airportLoadList with recently added airports

### ISSUE THREAD

**Issue by n8rzz** [n8rzz/atc#106]
New airports have been added post v3 and need to be added to the `airportLoadList.js` file.

**Comment by erikquinn** [comment]
Unless you're changing airports, shouldn't this be a non-issue, with a simple rebase before merging `n8rzz/release/3.1.0` into `zlsa/gh-pages`? All that was changed were airport files, an airline or two, and the load list.

**Comment by n8rzz** [comment]
@erikquinn and really the only concern is the load list.  everything else should be just fine,but if the new airports aren't in the load list, thats a problem.
