### ISSUE TITLE
Abstract current waypoint altitude and speed setting

### ISSUE THREAD

**Issue by n8rzz** [n8rzz/atc#124]
The following block is repeated multiple times in the fms, this needs to be abstracted.

```javascript
const curr = this.currentWaypoint;
if (prev && !curr.altitude) {
    curr.altitude = prev.altitude;
}

if (prev && !curr.speed) {
    curr.speed = prev.speed;
}

if (!curr.heading && curr.navmode === 'heading') {
    curr.heading = prev.heading;
}
```

**Comment by n8rzz** [comment]
**must be merged after n8rzz/atc#53 **

**Comment by n8rzz** [comment]
`feature/ATC-124` branch created, however, this work is a low priority

**Comment by n8rzz** [comment]
will likely be invalidated by n8rzz/atc#256

**Comment by erikquinn** [comment]
This issue was moved to openscope/openscope#77
