### ISSUE TITLE
Issuing 'takeoff' to departure still rolling on runway reply ' already airborne'

### ISSUE THREAD

**Issue by erikquinn** [n8rzz/atc#136]
See zlsa#738.

**Comment by n8rzz** [comment]
@erikquinn Is this still a valid issue?  The issue this links to references a fix for this being part of v3.1.0?

**Comment by erikquinn** [comment]
@n8rzz Don't think it's still valid. Perhaps I missed it in post-3.1.0-merge cleanup... or perhaps I was in a hurry and didn't *do* any post-merge issue cleanup... I'll get to that today or tonight.

**Comment by n8rzz** [comment]
@erikquinn no worries.  Thats why we have issues for stuff.  I like the ones we can close as 'Already fixed the glitch'.

**Comment by erikquinn** [comment]
This has been fixed. Closing.
