### ISSUE TITLE
Rerouting aircraft causes it to climb to unassigned altitude

### ISSUE THREAD

**Issue by n8rzz** [n8rzz/atc#155]
rerouting an aircraft (in this case from BSR.BSR2.KSFO to QUINN.BDEGA2.KSFO, they will climb of their own accord to very high altitude and not come down. They can be told to descend normally, but a strange altitude is being put in there. May or may not be related.

**Comment by Dabea** [comment]
I think this might be related When trying to reroute a spawned incoming plane get a `uncaught TypeError : cannot Read property  'altitude' of undefined` This takes place in src\assets\scripts\aircraft\FlightManagementSystem\AircraftFlightManagementSystem.js:1003

**Comment by erikquinn** [comment]
This issue was moved to openscope/openscope#86
