### ISSUE TITLE
aircraftInstanceModel.fms has a circular dependency with aircraftInstanceModel.fms.my_aircraft.fms

### ISSUE THREAD

**Issue by n8rzz** [n8rzz/atc#16]
`aircraftInstanceModel.fms` has a property `my_aircraft` which is a reference to the parent aircraft class.  By including this entire class, this also brings with it the `fms` property and it's `my_aircraft` property and so on and so on.

This is a circular dependency that _will_ adversely effect performance and could potentially cause the browser to crash.

**Comment by n8rzz** [comment]
This task will very likely identify places for refactor in order to remove the circular dependency. In that event, create new issues when those needs have been identified.  If the circular dependency can be easily resolved, do so under this ticket.

**Comment by n8rzz** [comment]
will likely be invalidated by n8rzz/atc#256

**Comment by erikquinn** [comment]
This issue was moved to openscope/openscope#57
