### ISSUE TITLE
Error when no altitude in waypoint

### ISSUE THREAD

**Issue by erikquinn** [n8rzz/atc#171]
![image](https://cloud.githubusercontent.com/assets/5103735/20726828/2258081c-b645-11e6-93df-b40aadc33f96.png)

**Comment by n8rzz** [comment]
@erikquinn do you have any specific steps to reproduce this error?

**Comment by erikquinn** [comment]
Duplicate of #137. I was in a hurry at the time so just posted it without any details. Looked into it, it is caused by using `caf cvs w 4r` at KJFK for a/c on the DEEZZ4, which only valid for Runways 31L and 31R.

Closing.
