### ISSUE TITLE
Errors thrown when `Leg` construction fails

### ISSUE THREAD

**Issue by erikquinn** [n8rzz/atc#175]
To Reproduce:

At KJFK, issue command `caf cvs w 4L` to an aircraft filed on the `DEEZZ4`. Will produce an error of:

`RouteModel.js:46 Invalid data type passed to RouteModel. Expected a string but received [object Object]`

This is due to it trying to construct a new `RouteModel` from the contents of `Leg.route`, which it expects to be a simple route string, but in this case, it was already an instance of `RouteModel`, so the construction fails. Thus, the `Leg` construction subsequently fails as well.

With the failure of the instantiation of the new `Leg`, the waypoints are not generated either. Thus, when `aircraft.fms.currentWaypoint` or `aircraft.fms.altitudeForCurrentWaypoint()` are called, there are no `Waypoint`s within the current `Leg`, so the app goes berserk with errors.

**Comment by erikquinn** [comment]
@n8rzz FYI: I pushed a small start to this to the `feature/ATC-175` branch. Keep it or trash it; either way it should provide some useful information.

**Comment by n8rzz** [comment]
@erikquinn so n8rzz/atc#154 shouldn't even be a thing?  Am I reading that correctly,  _every_ airport file should define `rwy`, `body` and `exitPoints`?

**Comment by erikquinn** [comment]
It depends on the type of procedure...

If it starts or ends at an airport, it should have a runway section (SIDs/STARs/IAPs, but not airways).

If it ends at the airport, it should have an entryPoint, if it begins at the airport it should have an exitPoint.

All procedures should have a body section.

**Comment by n8rzz** [comment]
yeah, I get what you're saying, we're on the same page there.

so what do we do about the airport files that current have only `body` sections?  because, currently, the `StandardRouteCollection` supports that case and I believe there are several airports that are set up with only body sections (I could be wrong though)

**Comment by n8rzz** [comment]
`feature/ATC-175` branch created
