### ISSUE TITLE
Video Maps are drawn incorrectly

### ISSUE THREAD

**Issue by erikquinn** [n8rzz/atc#176]
Alignment/drawing of video maps has been broken somehow. Works on `zlsa/gh-pages`, but not on `develop` (I'm using the deployed version on heroku since I'm at work without my git stuff)

![image](https://cloud.githubusercontent.com/assets/5103735/20817952/bca79734-b7f8-11e6-8fc4-38eb9f8d4553.png)

![image](https://cloud.githubusercontent.com/assets/5103735/20817965/cb0bc8cc-b7f8-11e6-8549-7fc063ef6e47.png)

**Comment by n8rzz** [comment]
I'll be this has something to do with n8rzz/atc#159
