### ISSUE TITLE
Create CommandAircraft class to handle execution of aircraft commands

### ISSUE THREAD

**Issue by n8rzz** [n8rzz/atc#181]
- [x] Create class that accepts an `AircraftInstanceModel` and a `CommandParser` object as parameters
- [x] move `run` methods to this class
- [x] update refs to `this` with aircraft
- [ ] address TODOs and FIXMEs
- [ ] simplify where possible
- [ ] abstract where possible
- [ ] consolidate where possible (DRY)
- [ ] add tests

**Comment by erikquinn** [comment]
This issue was moved to openscope/openscope#92
