### ISSUE TITLE
RunwayModel cleaning and improvements

### ISSUE THREAD

**Issue by n8rzz** [n8rzz/atc#182]
- [ ] add `_get` to `parse` method
- [ ] simplify
- [ ] investigate current implementations and optimize
- [ ] investigate pros/cons of implementing a RunwayCollection architecture
  - see: `AircraftConflict.checkProximity() #runwayRelationship`
  - see: `AirportModel.rwy.metadata`

---

- [ ] replace `airport` param with `airport.elevation`

**Comment by erikquinn** [comment]
This issue was moved to openscope/openscope#93
