### ISSUE TITLE
update findRandomExitPointForSIDIcao to handle invalid identifier

### ISSUE THREAD

**Issue by n8rzz** [n8rzz/atc#189]
this all pretains to the `StandardRouteCollection.findRandomExitPointForSIDIcao()` method

example:
- airport: KSFO
- command: `${CALLSIGN} sid offshore9`

- [ ] This should error in the ui and the console. 
- [ ] there should be a specific check for a valid routeCollection, which throws if one doesn't exist
- [ ] The property name `sid` should be renamed to `routeCollection`.
- [ ] add additional test case(s)

_note: will be invalidated by https://github.com/zlsa/atc/issues/752_

**Comment by erikquinn** [comment]
- [ ] ...and please rename to `findRandomExitPointforSID()`.

**Comment by n8rzz** [comment]
there's that pesky `icao` sneaking in, good call!

**Comment by n8rzz** [comment]
@erikquinn actually, will this method even be needed after we implement https://github.com/zlsa/atc/issues/752?  Or is that issue more of a 'moonshot' goal?  Do you have a timeframe in mind with that issue?

**Comment by erikquinn** [comment]
Hm. I guess not. :Smile:

**Comment by erikquinn** [comment]
And no that's no moonshot, it's kinda pathetic we don't do it already to be honest. Should be easy. Can be a next spring thing though.

**Comment by n8rzz** [comment]
like invalidated by n8rzz/atc#243 and n8rzz/atc#229

**Comment by erikquinn** [comment]
Covered by openscope/openscope#120. Closing.
