### ISSUE TITLE
Normalize spaces with template strings

### ISSUE THREAD

**Issue by n8rzz** [n8rzz/atc#192]
Here is an example using `caf cvs to`

<img width="476" alt="screen shot 2016-12-12 at 10 01 53 pm" src="https://cloud.githubusercontent.com/assets/3325985/21127190/adce5e5c-c0b6-11e6-9550-a47776d4c339.png">

The issue is a result of some vars being used within template strings having spaces on the right side.

- [ ] All template strings should have spaces on the left side only

```javascript
var str = 'AA123';

// used thusly
return `${st} cleared for takeoff`
```
- [ ] any string set to a var should not include spaces

```javascript
// bad
var str = 'AA123 ';

// good
var str = 'AA123';
```

Most of the offenders here should be within the `AircraftInstanceModel`. Feel free to search the app for all template strings and adjust spacing on any the require it.

**Comment by Dabea** [comment]
I have found a few things in `AircraftInstanceModel` that should help with spacing.  I searched though many other files but did not see anything else. If you have any other files that might be a good candidate to be searched though let me know.
