### ISSUE TITLE
After completing flightplan, aircraft all turn to heading 360

### ISSUE THREAD

**Issue by erikquinn** [n8rzz/atc#206]
Just like it sounds. Easy to reproduce. :wink: 

![image](https://cloud.githubusercontent.com/assets/5103735/21213908/6dee161e-c265-11e6-918c-0e7af8ec478e.png)

They should instead continue on the heading they were tracking when they passed the final Waypoint in the fms.

**Comment by n8rzz** [comment]
I've been seeing this one for a while, I just thought that was expected behavior?  Whoops.

**Comment by erikquinn** [comment]
The `Leg` is not being constructed correctly when called from `AircraftInstanceModel.cancelFix()`. Investigating now.

**Comment by erikquinn** [comment]
`Leg.js:308`
