### ISSUE TITLE
Strange departures

### ISSUE THREAD

**Issue by panther2** [n8rzz/atc#210]
Experienced on https://atc-dev-pr-198.herokuapp.com/ 
at EDDT:

Departing aircrafts show a strange and permanently changing heading:

![1kl](https://cloud.githubusercontent.com/assets/20812775/21219063/77375624-c2b3-11e6-9493-a85de6ac74c8.png)
![2kl](https://cloud.githubusercontent.com/assets/20812775/21219064/773b472a-c2b3-11e6-9caa-6e45abce1804.png)
![3kl](https://cloud.githubusercontent.com/assets/20812775/21219065/773e6e00-c2b3-11e6-8e8f-6686808e51fc.png)
![4kl](https://cloud.githubusercontent.com/assets/20812775/21219066/7741fcdc-c2b3-11e6-88e5-c644a1cf3515.png)

If I had taken a fifth screenshot it would have shown a heading similar to the second image.

To reproduce move to EDDT, let a plane takeoff after `caf` and watch the permanently changing blue heading line.

**Comment by n8rzz** [comment]
@panther2 did the aircraft end up flying in the same path that is drawn?  Or did it correctly follow the sid route all the way out of the airspace?

**Comment by n8rzz** [comment]
from what I'm seeing, this looks to be a result of how we are drawing the future path of an aircraft but doesn't appear to affect the actual route.

**Comment by panther2** [comment]
I was wondering because it appears not to happen for example on EDDM.

**Comment by erikquinn** [comment]
It probably has to do with how close the fixes are together at this airport in particular. When the projection logic steps forward in time to figure out where the aircraft WILL be, it sometimes takes steps too large, and thinks it did not reach a waypoint it kinda "jumped over", and thus turns around to go back to it. See zlsa#456 and zlsa#581.

**Comment by panther2** [comment]
Interesting, thanks for the references.
