### ISSUE TITLE
Create SpawnScheduler class

### ISSUE THREAD

**Issue by n8rzz** [n8rzz/atc#235]
used to register spawns for departures and arrivals created with data from airport json.  

- should be a collection of `setInterval()`s each with some sort of a createAircraft callback
- callback should be called with info defined in departure/arrival section of airport.json
- interval delay is from frequency defined in airport.json
- intervals should be cancelable
- intervals should clear when an airport is changed
- should not create/destroy anything other than intervals
- tests

**Comment by n8rzz** [comment]
n8rzz/atc#243

**Comment by erikquinn** [comment]
This issue was moved to openscope/openscope#133
