### ISSUE TITLE
Prevent or penalize landings of "departure" aircraft

### ISSUE THREAD

**Issue by eliuuk** [n8rzz/atc#246]
I was just messing around on the game (live version of course!) and I managed to successfully land a departing aircraft through guiding it onto the ILS. Making the aircraft takeoff was also possible. 

Although not major, restricting a departing aircraft from landing should be a feature despite it being a feature that could be used for emergencies.

**Comment by n8rzz** [comment]
@indianbhaji I'm not sure I follow.  Are you suggesting that it should _not_ be allowed to re-route a departing aircraft to land back at the airport?

**Comment by eliuuk** [comment]
> Are you suggesting that it should not be allowed to re-route a departing aircraft to land back at the airport?

Exactly that.

**Comment by n8rzz** [comment]
I'm not sure I agree with that.  I can think of a few instances where that should be allowed.  But I'm no expert 😉 

@erikquinn thoughts?

**Comment by erikquinn** [comment]
Yeah, I'm not sure. I can see both sides. Either way, I do not think it is worth putting any time into changing what we've got in this regard. Closing.
