### ISSUE TITLE
Build term dictionary/glossary

### ISSUE THREAD

**Issue by n8rzz** [n8rzz/atc#247]
There is a lot of aviation-specific language used throughout the app.  It may be helpful to have a dictionary or glossary of those terms with quick definitions and links to more info for the aviation novice.

**Comment by n8rzz** [comment]
Some words/terms that should be included:
- preSpawn
- spawnPattern
- StandardRoute
- RouteString
- waypoint
- fix 
- ILS
- airspace
- runway naming patterns
- flight level, msl, agl altitudes

_there will be more (and I'll add them here as I run into them). these are the ones I keep running into that I feel need some documentation_

**Comment by erikquinn** [comment]
Covered by openscope/openscope#146. Closing.
