### ISSUE TITLE
Create a new class between App and everything else

### ISSUE THREAD

**Issue by n8rzz** [n8rzz/atc#252]
We need a class that can act as a conductor between the `App`, with the game loop, and everything else.  This class would be responsible for orchestrating initial data load, airport change as well as providing a launching point for additional view classes that we will need in the future.

Instead of `App` creating all the top level classes, `App` would instantiate this class and it would then create everything else.

- [ ] accepts `$element`, `airportLoadList`, `initialAirportIcao` as parameters
- [ ] provides facade methods that are run within the `App` game loop
- [ ] provides callback method(s) that can be sent to various classes for handling events (ex: airportChange)

**Comment by erikquinn** [comment]
This issue was moved to openscope/openscope#137
