### ISSUE TITLE
create SpawnPatternPeriodCalculator class

### ISSUE THREAD

**Issue by n8rzz** [n8rzz/atc#261]
this is an enhancement of n8rzz/atc#243.

Calculation of delay periods requires a fair amount of class properties and methods.  This issue will:

- [ ] move those props and methods to their own class such that the `SpawnPatternModel.getNextDelayValue()` will call `SpawnPatternPeriodCalculator.getNextDelayValue()`
- [ ] Add tests

**Comment by erikquinn** [comment]
This issue was moved to openscope/openscope#143
