### ISSUE TITLE
create RouteBuilder class and smooth out RouteModel

### ISSUE THREAD

**Issue by n8rzz** [n8rzz/atc#262]
from n8rzz/atc#251 :
>Way I see it, the RouteModel should be all encompassing of an entire "route", and the individual pieces are another class. Here, RouteModel is really being used like what I would call a 'RouteSegmentModel' or 'SimpleRouteSegmentModel', which differs from a 'ProcedureRouteSegmentModel'. An array of these things should make up a 'RouteModel'

**Comment by erikquinn** [comment]
This issue was moved to openscope/openscope#144
