### ISSUE TITLE
#243 bugs

### ISSUE THREAD

**Issue by n8rzz** [n8rzz/atc#263]
blanked bugfix branch to hold issues found with #243 

#### airport doesn't load
- [x] OTHH
- [x] WSSS
- [x] WMKP
- [x] ZSPD

#### misc
- [ ] ~FASTGA icao is disregarded (ie. FASTGA872zz) - should be N872ZZ~ [openscope#164](https://github.com/openscope/openscope/issues/164)

**Comment by erikquinn** [comment]
My two cents: Just remove em from the load list.

**Comment by n8rzz** [comment]
I've already fixed most of them, actually.
