### ISSUE TITLE
Rename AreaModel to AirspaceModel

### ISSUE THREAD

**Issue by n8rzz** [n8rzz/atc#36]

**Comment by n8rzz** [comment]
It looks like most of the logic needed here is already covered with the `AreaModel` class.

**Comment by erikquinn** [comment]
> It looks like most of the logic needed here is already covered with the AreaModel class.

Correct, that was what it was made for actually.

**Comment by n8rzz** [comment]
yeah, I should have looked into that a little more before I started coding a new class. 🤕  I had one, then I started implementing the `AreaClass` within the new one and had the "I'm an idiot!" moment.  ugh, I should know better.

I ended up just re-working the existing class and adding tests.  I will probably just rename it to `AirspaceModel` and move it to be within the airport directory so its concerns are a little clearer.  

You can check the MR to see what I ended up with.  This will be for `develop` though, so v3.0.x.

**Comment by n8rzz** [comment]
- [ ] rename `AreaModel` to `AirspaceModel`
- [ ] add tests
- [ ] update implementations
