### ISSUE TITLE
Allow only one modal window open at a time

### ISSUE THREAD

**Issue by n8rzz** [n8rzz/atc#38]
It is possible to have _all_ modal windows open at once. This is confusing for the user.

- [ ] Add a way to close an already open modal

- Perhaps  create a whole new ModalController/ModalView class to separate and easily isolate the concerns here.

<img width="633" alt="screen shot 2016-10-15 at 3 07 12 pm" src="https://cloud.githubusercontent.com/assets/3325985/19413068/4ddb0202-92e9-11e6-96ed-d55841b99c64.png">

**Comment by erikquinn** [comment]
This issue was moved to openscope/openscope#61
