### ISSUE TITLE
Update instances of `prop` to use `this`

### ISSUE THREAD

**Issue by n8rzz** [n8rzz/atc#43]
Update direct usages of `prop` inside classes.  Instead of a class setting class properties to `prop` use `this`.

However, for now, we must maintain the references to the original `prop` values so we don't break everything.

the current workaround is:
```javascript
const aircraft = {};

export default class Aircraft {
    constructor() {
        this.aircraft = aircraft;
        prop.aircraft = aircraft;
    }
```

This way we can maintain the original props, but still use class properties in the usual way.

---

There are also references to `prop` values from other classes sprinkled throughout, those are not being refactored [yet] with this issue.

**Comment by n8rzz** [comment]
work started on branch `feature/ATC-43`

**Comment by n8rzz** [comment]
`gameController` updated with n8rzz/atc#96

**Comment by erikquinn** [comment]
This issue was moved to openscope/openscope#62
