### ISSUE TITLE
Abstract inline fix object out of ArrivalBase

### ISSUE THREAD

**Issue by n8rzz** [n8rzz/atc#56]
These lines are problematic:
```javascript
for (let i = 0; i < options.fixes.length; i++) {
    this.fixes.push({ fix: options.fixes[i] });
}
```

`this.fixes` has a very specific use and having these inline objects is somewhat confusing.  This needs improvement.

**Comment by n8rzz** [comment]
n8rzz/atc#243

**Comment by erikquinn** [comment]
This issue was moved to openscope/openscope#64
