### ISSUE TITLE
Airports with negative elevation cause funkiness with Aircraft

### ISSUE THREAD

**Issue by n8rzz** [n8rzz/atc#6]
Example airport: `EHAM`

With a fix in place for #5, a new issue has presented itself.  When the airport is first loaded all the departures crash due to terrain collisions.  Additionally, any new departures spawn directly on a runway and are in the process of taking off as though they have already been cleared.

I suspect that this has something to do with the `AircraftInstanceModel` defaulting the altitude to 0 and only setting an altitude, in the `parse` method if one is passed in.  I was playing with something like this:

``` javascript
parse(data) {
    this.altitude = _get(data, 'altitude', window.airportController.airport.current.elevation);

    if (this.altitude !== 0) {
        this.fms.setCurrent({ altitude: this.altitude });
    }
}
```

But this is a rather short-sided solution.  It solves this problem but creates new ones.  I need to dig into how altitude, elevation and the Aircraft are all working together in order for me to get this one fixed properly.

**Comment by erikquinn** [comment]
For what it's worth, they actually appear to be crashing into each other, not the terrain... which is interesting, because I thought the conflict detection logic had been updated to deal with aircraft that were "on the ground", but not having an "altitude" of "0", but maybe not.

It may be wise to use a new aircraft property to deal with this, either a value for a radar altimeter (height above terrain) or maybe even a simple binary WOW flag, which is heavily used in logic of real avionics and such. We can always subtract the elevation of the airport I suppose, but it's probably wisest not to do it this way, so there would be native support for things like secondary satellite airports, etc.

**Comment by erikquinn** [comment]
And sorry, "WOW" as in "weight-on-wheels", just like it sounds: on the ground or in the air.

**Comment by n8rzz** [comment]
I'd be hesitant to add another property to the Aircraft, that is already a very large model.  

From what you are describing, it sounds like this may just be an update in logic somewhere.  The airplanes are not considered 'on the ground' and thus must be inflight and because they are spawning as departures, they are all in the same spot.  Hence the collisions?

**Comment by n8rzz** [comment]
another existing issue https://github.com/zlsa/atc/issues/680 suggests that the way altitudes and elevations are handled in general may need to be looked at.

**Comment by erikquinn** [comment]
> I'd be hesitant to add another property to the Aircraft, that is already a very large model.

Yeah. A great majority of them can actually be removed/consolidated/improved/etc, but that's an unneccessary undertaking at this stage. We do need to reevaluate the best way to deal with the altitude/elevation of aircraft.

**Comment by erikquinn** [comment]
@n8rzz why not 3.0.0?

**Comment by n8rzz** [comment]
We _could_ do it on v3.  

My concerns with making this change is that it will have a lot of side effects and then the potential to create more bugs.  If we do decide to do this now, I would want to address some of the other issues with the `AircraftInstanceModel` as well.

We could totally do it now, if that's what you would like.  It will obviously push out v3 a little ways, which I have tentatively finishing at the end of this month.  Maybe it'll go quick, but I really don't think that will be the case.

**Comment by erikquinn** [comment]
All I know is we can't reasonably push a release where an entire airport (EHAM) is completely nonfunctional. The Dutch players would be on us like white on rice... haha

And I don't think this really needs a full and proper solution at this stage, but it definitely needs to be sufficiently patched so EHAM is usable. Can't we achieve this without necessitating significant work on the `AircraftInstanceModel`? I'm pretty confident this would actually be a relative cakewalk of a fix, and think we can still continue with that timeline.

**Comment by n8rzz** [comment]
I agree, it should be playable. My concern is the side effects.  But you're right, the Dutch guys wouldn't be happy. 

I'll start digging into it tonight. I will also try to go in with a scalpel instead of a wrecking ball.

**Comment by erikquinn** [comment]
I actually already did most of it real quick last night, but arrivals still
aren't disappearing after they land. Check the `bugfix/ATC-6` branch.

EQ

**Comment by n8rzz** [comment]
Like our CEO says, `Fuck Yeah!`

I'll take a peak at that branch, tonight.

**Comment by n8rzz** [comment]
So, without looking at what you'd done, I starting trying to track this thing down for myself.  Just for the adventure of it...

I stumbled on to more or less the same solution you did.  All these problems stem from initializing the `altitude` property to `0` and then using it before it gets update.  The initialization is a good thing, I'm a big fan of initializing with invalid values and then setting the correct ones in another method.  The problem is that the property doesn't have a chance to update, or isn't updated at all, before the `AircraftConflict` class gets a hold of it.

Peaking through your stuff, I was on the same track you were on.  Do you want to just finish this one up and I'll give you some feedback in the PR?

**Comment by erikquinn** [comment]
Sure, I'll get to it tomorrow morning before work.
