### ISSUE TITLE
Range rings are too bright

### ISSUE THREAD

**Issue by n8rzz** [n8rzz/atc#62]
https://github.com/zlsa/atc/issues/711

**Comment by n8rzz** [comment]
Outer ring color is correct, inner rings need to have a lower opacity.
v2:
<img width="291" alt="screen shot 2016-11-07 at 4 49 42 pm" src="https://cloud.githubusercontent.com/assets/3325985/20079429/3ba85c46-a50a-11e6-8c67-2c90ad84e85d.png">

v3:
<img width="423" alt="screen shot 2016-11-07 at 4 49 34 pm" src="https://cloud.githubusercontent.com/assets/3325985/20079435/452670be-a50a-11e6-8614-7dea0a3ade7a.png">

**Comment by erikquinn** [comment]
Eventually, this and numerous other display settings will need to have a UI to adjust various things. I can provide more detail later, but just wanted to throw it out there that that will be an eventuality.

**Comment by n8rzz** [comment]
Added #76 for now. feel free to make a list of things that should be changeable.  Perhaps this should actually be an issue in the main repo?  

This sounds like it would be a fun problem to solve, someday.  In the mean time we can document it so it is at least visible.

**Comment by erikquinn** [comment]
Yeah, it's kind of just one of many things on my "pipe dream" list, so I haven't written up any issues for them until I get serious about doing one of them. But it should be one of the first couple additions in the near future, so I'll write up a quick new issue for it.

Added zlsa#716

**Comment by n8rzz** [comment]
feel free to add to #76
