### ISSUE TITLE
Readback given after A/C are cleared for T/O is buggy

### ISSUE THREAD

**Issue by n8rzz** [n8rzz/atc#64]
https://github.com/zlsa/atc/issues/711

**Comment by n8rzz** [comment]
<img width="425" alt="screen shot 2016-11-07 at 4 51 40 pm" src="https://cloud.githubusercontent.com/assets/3325985/20079493/8c43488c-a50a-11e6-9884-1c37c8b7295e.png">

**Comment by Fechulo** [comment]
I found a new bug somewhat related to this one. When a departing aircraft leaves the airspace without being cleared to it's departure gate, the fix name shows up as 'undefined':
![dep](https://cloud.githubusercontent.com/assets/13125311/20115147/1541e3fc-a5ef-11e6-86ac-42d27ba2c078.png)
Furthermore, arriving aircraft who leave the airspace warn the player twice (once as an arrival and once as a departure):
![arr](https://cloud.githubusercontent.com/assets/13125311/20115216/52019990-a5ef-11e6-9192-dac12393bfdf.png)

**Comment by n8rzz** [comment]
@Fechulo I added a new issue (n8rzz/atc#72 ) for easier tracking.  This looks to be a different problem than was originally reported here, though I'm guessing it will be a similar solution.

Either way, its on the board.  Thanks!!
