### ISSUE TITLE
Allow user to change UI settings

### ISSUE THREAD

**Issue by n8rzz** [n8rzz/atc#76]
The user should have access to a UI that allows them to adjust various basic things about the way the markings on the scope are displayed. This would include adjustments to:

- brightness of aircraft targets, data blocks, control symbols
- brightness of background color
- brightness and radius of range rings
- brightness of video map markings
- center of range rings
- default direction of data block leader lines
- default length of data block leader lines
- default length of PTLs (see zlsa#715)

---

- [ ] create UiSettingsModel
- [ ] implement new class into CanvasController

**Comment by erikquinn** [comment]
zlsa#716

**Comment by erikquinn** [comment]
Covered by openscope/openscope#15 and openscope/openscope#115. Closing.
