### ISSUE TITLE
Decouple data loads from creation of instances

### ISSUE THREAD

**Issue by n8rzz** [n8rzz/atc#78]
All of the data we need is available once we know the current airport.  Why not load _all_ the airlines and _all_ the aircraft types into collections that can then be referenced when a new aircraft spawns.

load airport -> load airlines -> load aircraft for airlines (airline fleets) -> begin spawning departures/arrivals

**Comment by n8rzz** [comment]
![atc init](https://cloud.githubusercontent.com/assets/3325985/20204972/49031ae2-a79a-11e6-8dbe-0c68c70d9ba8.jpg)

**Comment by erikquinn** [comment]
This issue was moved to openscope/openscope#66
