### ISSUE TITLE
Centralize window methods to class constructors and create class property

### ISSUE THREAD

**Issue by n8rzz** [n8rzz/atc#98]
for a class that uses a method on another class that is attached to the `window`

- [ ] add a class property for each window class: `window.airportController` becomes `this.airportController`
- [ ] centralize window methods to topmost parent class and pass needed window methods to children on demand

---

This is the next step in moving away from window methods.  The endGame here is to instantiate all of the parent classes with everything they need, without any assistance from the `window`.

**Comment by n8rzz** [comment]
this might need some more testing, performance takes a hit with `timewarp = 50` and an aircraft is selected.

**Comment by n8rzz** [comment]
made big strides here with n8rzz/atc#243

**Comment by erikquinn** [comment]
This issue was moved to openscope/openscope#71
