### ISSUE TITLE
Convert appropriate classes to static classes

### ISSUE THREAD

**Issue by n8rzz** [n8rzz/atc#99]
Are there reasons we shouldn't do this?  There are several classes that are essentially static, but are being used as instances

- [ ] GameController
- [ ] CanvasController
- [ ] AirportController
- [ ] AircraftController
- [ ] AirlineController

---

There may be more than what is listed above.  It might not make sense to convert some to static.  It really only makes sense with a class like GameController and CanvasController where other classes use their methods and internal properties.

Static classes may not be the best solution.  More research and discussion is needed in order to flesh this out.

**Comment by erikquinn** [comment]
This issue was moved to openscope/openscope#72
